CREATE TABLE [dbo].[EGifts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [MerchantId] UNIQUEIDENTIFIER NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[GiftAmount] DECIMAL(13, 2) NOT NULL,
	[DateValid] DATETIME NOT NULL
)
